### ISSUE TITLE
--max-semi-space-size doc is wrong after Node 18

### ISSUE THREAD

**Issue by joebowbeer** [ztec/blog#4]
Thanks for writing content/post/tech/node.js-20-upgrade-heap-issues !

I created an [issue](https://github.com/nodejs/node/issues/55487) for the node docs and a [PR](https://github.com/nodejs/node/pull/55495) to update the docs

**Comment by ztec** [comment]
:astonished: Nice. Well done.

And Thank you :hugs:. I will include it in an update.

**Comment by joebowbeer** [comment]
Slight correction: https://github.com/nodejs/node/pull/55812
